FEATURE_METADATA = {
    "time_since_last_tx": {'descricao': 'Tempo desde a última transação', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'temporal', 'status': 'inativa', 'in_model': False},
    "tx_time_seconds": {'descricao': 'Tempo da transação em segundos', 'tipo': 'integer', 'fonte': 'temporal', 'grupo': 'temporal', 'status': 'ativa', 'in_model': True},
    "tx_time_days": {'descricao': 'Dias da transação desde a construção do banco', 'tipo': 'integer', 'fonte': 'temporal', 'grupo': 'temporal', 'status': 'ativa', 'in_model': True},
    "tx_hour": {'descricao': 'Hora da transação', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'temporal', 'status': 'inativa', 'in_model': False},
    "weekday_of_day": {'descricao': 'Dia da semana da transação', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'temporal', 'status': 'inativa', 'in_model': False},
    "month": {'descricao': 'Mês da transação', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'temporal', 'status': 'ativa', 'in_model': True},
    "year": {'descricao': 'Ano da transação', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'temporal', 'status': 'inativa', 'in_model': False},
    "is_weekend": {'descricao': 'Se é fim de semana', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'flag', 'status': 'inativa', 'in_model': False},
    "month_reference": {'descricao': 'Mês de referência', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'temporal', 'status': 'descartada', 'in_model': False},
    "tx_day": {'descricao': 'Dia da transação', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'temporal', 'status': 'inativa', 'in_model': False},
    "tx_month": {'descricao': 'Mês da transação', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'temporal', 'status': 'descartada', 'in_model': False},
    "tx_period_day": {'descricao': 'Periodo da transação (Manhã, tarde, noite ou madrugada)', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'não categorizado', 'status': 'inativa', 'in_model': False},
    "distance_customer_terminal": {'descricao': 'Distância entre cliente e terminal', 'tipo': 'float', 'fonte': 'geográfica', 'grupo': 'espacial', 'status': 'inativa', 'in_model': False},
    "is_single_tx_customer": {'descricao': 'Cliente com apenas uma transação', 'tipo': 'float', 'fonte': 'comportamental', 'grupo': 'flag', 'status': 'inativa', 'in_model': False},
    "repeated_tx": {'descricao': 'Transações repetidas pelo cliente', 'tipo': 'float', 'fonte': 'comportamental', 'grupo': 'flag', 'status': 'inativa', 'in_model': False},
    "outlier_tx": {'descricao': 'Transação com valor fora do padrão', 'tipo': 'float', 'fonte': 'comportamental', 'grupo': 'flag', 'status': 'ativa', 'in_model': True},
    "high_value_tx": {'descricao': 'Se a transação é um valor alto (3 vezes acima da média)', 'tipo': 'float', 'fonte': 'comportamental', 'grupo': 'flag', 'status': 'ativa', 'in_model': True},
    "unusual_hour": {'descricao': 'Transações em horário incomum', 'tipo': 'float', 'fonte': 'comportamental', 'grupo': 'flag', 'status': 'inativa', 'in_model': False},
    "frequent_tx": {'descricao': 'Transações com intervalo muito curto', 'tipo': 'float', 'fonte': 'comportamental', 'grupo': 'flag', 'status': 'inativa', 'in_model': False},
    "consecutive_transactions_same_terminal": {'descricao': 'Várias transações consecutivas no mesmo terminal?', 'tipo': 'float', 'fonte': 'comportamental', 'grupo': 'flag', 'status': 'inativa', 'in_model': False},
    "mean_amount": {'descricao': 'Média do valor das transações', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "std_amount": {'descricao': 'Desvio padrão do valor das transações', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "tx_amount_median_ratio": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'relacional_temporal', 'status': 'ativa', 'in_model': True},
    "tx_amount_to_mean_ration": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'relacional_temporal', 'status': 'ativa', 'in_model': True},
    "nb_tx_hour": {'descricao': 'Hora da transação', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'temporal', 'status': 'inativa', 'in_model': False},
    "tx_amount_hour_mean": {'descricao': 'Média do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "tx_amount": {'descricao': 'Valor da transação', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'estatística', 'status': 'ativa', 'in_model': True},
    "mean_time_between_txs": {'descricao': 'Tempo médio entre transações', 'tipo': 'float', 'fonte': 'temporal', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "std_time_between_txs": {'descricao': 'Desvio padrão do tempo entre transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "tx_amount_variation": {'descricao': 'Variação percentual do valor da transação', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "count_amount_per_customer_last_1h": {'descricao': 'Contagem de transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "total_amount_per_customer_last_1h": {'descricao': 'Total acumulado das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "mean_amount_per_customer_last_1h": {'descricao': 'Média do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "std_amount_per_customer_last_1h": {'descricao': 'Desvio padrão do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "median_amount_per_customer_last_1h": {'descricao': 'Mediana do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "max_amount_per_customer_last_1h": {'descricao': 'Valor máximo das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "amount_zscore_per_customer_last_1h": {'descricao': 'Z-score do valor da transação', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'zscore', 'status': 'ativa', 'in_model': True},
    "count_amount_per_customer_last_2h": {'descricao': 'Contagem de transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "total_amount_per_customer_last_2h": {'descricao': 'Total acumulado das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "mean_amount_per_customer_last_2h": {'descricao': 'Média do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "std_amount_per_customer_last_2h": {'descricao': 'Desvio padrão do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "median_amount_per_customer_last_2h": {'descricao': 'Mediana do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "max_amount_per_customer_last_2h": {'descricao': 'Valor máximo das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "amount_zscore_per_customer_last_2h": {'descricao': 'Z-score do valor da transação', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "count_amount_per_customer_last_4h": {'descricao': 'Contagem de transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "total_amount_per_customer_last_4h": {'descricao': 'Total acumulado das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "mean_amount_per_customer_last_4h": {'descricao': 'Média do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "std_amount_per_customer_last_4h": {'descricao': 'Desvio padrão do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "median_amount_per_customer_last_4h": {'descricao': 'Mediana do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "max_amount_per_customer_last_4h": {'descricao': 'Valor máximo das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "amount_zscore_per_customer_last_4h": {'descricao': 'Z-score do valor da transação', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "count_amount_per_customer_last_8h": {'descricao': 'Contagem de transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "total_amount_per_customer_last_8h": {'descricao': 'Total acumulado das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "mean_amount_per_customer_last_8h": {'descricao': 'Média do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "std_amount_per_customer_last_8h": {'descricao': 'Desvio padrão do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "median_amount_per_customer_last_8h": {'descricao': 'Mediana do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "max_amount_per_customer_last_8h": {'descricao': 'Valor máximo das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "amount_zscore_per_customer_last_8h": {'descricao': 'Z-score do valor da transação', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "count_amount_per_customer_last_12h": {'descricao': 'Contagem de transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "total_amount_per_customer_last_12h": {'descricao': 'Total acumulado das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "mean_amount_per_customer_last_12h": {'descricao': 'Média do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "std_amount_per_customer_last_12h": {'descricao': 'Desvio padrão do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "median_amount_per_customer_last_12h": {'descricao': 'Mediana do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "max_amount_per_customer_last_12h": {'descricao': 'Valor máximo das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "amount_zscore_per_customer_last_12h": {'descricao': 'Z-score do valor da transação', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "count_amount_per_customer_last_24h": {'descricao': 'Contagem de transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "total_amount_per_customer_last_24h": {'descricao': 'Total acumulado das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "mean_amount_per_customer_last_24h": {'descricao': 'Média do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "std_amount_per_customer_last_24h": {'descricao': 'Desvio padrão do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "median_amount_per_customer_last_24h": {'descricao': 'Mediana do valor das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'inativa', 'in_model': False},
    "max_amount_per_customer_last_24h": {'descricao': 'Valor máximo das transações', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "amount_zscore_per_customer_last_24h": {'descricao': 'Z-score do valor da transação', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'rolling_window', 'status': 'ativa', 'in_model': True},
    "ratio_mean_amount_per_customer_last_1h_to_2h": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'estatística', 'grupo': 'relacional_temporal', 'status': 'inativa', 'in_model': False},
    "ratio_total_transactions_per_customer_last_1h_to_2h": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'relacional_temporal', 'status': 'ativa', 'in_model': True},
    "ratio_mean_amount_per_customer_last_1h_to_4h": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'relacional_temporal', 'status': 'inativa', 'in_model': False},
    "ratio_total_transactions_per_customer_last_1h_to_4h": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'relacional_temporal', 'status': 'inativa', 'in_model': False},
    "ratio_mean_amount_per_customer_last_1h_to_8h": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'relacional_temporal', 'status': 'inativa', 'in_model': False},
    "ratio_total_transactions_per_customer_last_1h_to_8h": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'relacional_temporal', 'status': 'inativa', 'in_model': False},
    "ratio_mean_amount_per_customer_last_1h_to_12h": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'relacional_temporal', 'status': 'inativa', 'in_model': False},
    "ratio_total_transactions_per_customer_last_1h_to_12h": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'relacional_temporal', 'status': 'inativa', 'in_model': False},
    "ratio_mean_amount_per_customer_last_1h_to_24h": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'relacional_temporal', 'status': 'ativa', 'in_model': True},
    "ratio_total_transactions_per_customer_last_1h_to_24h": {'descricao': 'Razão entre janelas de tempo', 'tipo': 'float', 'fonte': 'transacional_temporal', 'grupo': 'relacional_temporal', 'status': 'inativa', 'in_model': False},
    "is_fraud": {'descricao': 'Variável alvo indicando se a transação é fraudulenta', 'tipo': 'bool', 'fonte': 'rótulo', 'grupo': 'target', 'status': 'target', 'in_model': False},
}


def gerar_feature_book(df, metadata_dict):
    """Gera um DataFrame com os metadados das features presentes no DataFrame."""
    import pandas as pd
    book = []
    for col in df.columns:
        meta = metadata_dict.get(col, {
            "descricao": "N/A",
            "tipo": str(df[col].dtype),
            "fonte": "desconhecida",
            "grupo": "não categorizado",
            "status": "inativa",
            "in_model": False
        })
        book.append({"nome": col, **meta})
    return pd.DataFrame(book)